# Generated by Django 4.1.5 on 2023-01-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=20, verbose_name='Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeJogo', models.CharField(max_length=20, verbose_name='Nome')),
                ('person', models.CharField(max_length=20, verbose_name='Personagem')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('generoJogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.generojogo')),
            ],
        ),
    ]
